<?php
$tapFiliateData = $block->getAccountData();
?>
<?php if ( $tapFiliateData != false): ?>

    <script type="text/javascript">
        (function (t, a, p) {
            t.TapfiliateObject = a;
            t[a] = t[a] || function () {
                (t[a].q = t[a].q || []).push(arguments)
            }
        })(window, 'tap');

        tap('create', '<?php echo $tapFiliateData['account'] ?>');
    </script>
<?php endif; ?>